# Jupyter Notebook für Aspekte der Datenanalyse
am Beispiel von Fraud Detection in Financial Transactions

#### Ausführung der notwendigen Imports

In [248]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

from src.config import CLEAN_TRANSACTIONS_PATH

#### Einlesen des Datensatzes

In [249]:
df = pd.read_csv(CLEAN_TRANSACTIONS_PATH)

df["Fraud_Label_str"] = df["Fraud_Label"].map({
    0: "Non-Fraud",
    1: "Fraud"
})

## Deskriptive Analyse

Die deskriptive Analyse dient dazu, historische Daten zu beschreiben,
zusammenzufassen und zu visualisieren, um zu erkennen, was in der Vergangenheit
passiert ist.

Dabei werden insbesondere Verteilungen, Häufigkeiten, Trends und Muster
untersucht. Ziel ist es, ein grundlegendes Verständnis des Datensatzes
zu schaffen und erste Auffälligkeiten sichtbar zu machen.

---

## Business-Fragestellungen der deskriptiven Analyse

1. Wie hoch ist der Anteil von Fraud- und Non-Fraud-Transaktionen?

2. Wie verteilen sich die Transaktionsbeträge im Datensatz?

3. Zu welchen Tageszeiten finden die meisten Transaktionen statt?

4. Zu welchen Uhrzeiten treten die meisten Betrugsfälle auf?

5. Welche Zahlungsmethoden werden am häufigsten verwendet?

6. Welche Gerätetypen werden am häufigsten für Transaktionen genutzt?

7. Welche Standorte weisen die meisten Transaktionen auf?

8. Welche Händlerkategorien dominieren den Datensatz?

9. Wie häufig treten fehlgeschlagene Transaktionen innerhalb der letzten 7 Tage auf?

10. Wie unterscheiden sich Fraud- und Non-Fraud-Transaktionen hinsichtlich ihrer zentralen Merkmale?

---

## Ziel der deskriptiven Analyse

Das Ziel der deskriptiven Analyse besteht darin, den Datensatz zunächst
grundlegend zu verstehen, zentrale Muster sichtbar zu machen und eine
fundierte Basis für die nachfolgenden diagnostischen, prädiktiven und
präskriptiven Analysen zu schaffen.

#### 1.1 Datenverständnis

##### Größe des Datensatzes

Zunächst wird untersucht, wie groß der Datensatz ist.
Dabei werden die Anzahl der Zeilen sowie die Anzahl der Spalten bestimmt.

In [250]:
print(f"Anzahl Zeilen: {df.shape[0]}")
print(f"Anzahl Spalten: {df.shape[1]}")

Anzahl Zeilen: 49998
Anzahl Spalten: 23

##### Erste Vorschau auf die Daten

Durch eine erste Vorschau können Struktur, Inhalte und erste Auffälligkeiten
im Datensatz betrachtet werden.

In [252]:
df.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Account_Balance,Amount_to_Balance_Ratio,Device_Type,Location,Merchant_Category,IP_Address_Flag,...,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Hour,Is_Weekend,Fraud_Label,Fraud_Label_str
0,txn_0,user_8270,95.97,atm withdrawal,93915.02,0.001022,mobile,new york,restaurants,0,...,0,visa,27,4610.43,pin,0.3773,6,0,0,Non-Fraud
1,txn_1,user_1860,55.41,atm withdrawal,91495.28,0.000606,laptop,tokyo,clothing,0,...,1,visa,93,2284.15,pin,0.5871,10,0,0,Non-Fraud
2,txn_10,user_2685,283.26,pos,48484.20,0.005842,tablet,mumbai,electronics,0,...,0,mastercard,78,4273.45,password,0.6237,5,1,0,Non-Fraud
3,txn_100,user_6056,57.24,atm withdrawal,89219.38,0.000642,mobile,tokyo,groceries,0,...,0,visa,116,3446.99,biometric,0.0785,10,0,0,Non-Fraud
4,txn_1000,user_9038,58.43,atm withdrawal,40090.04,0.001457,laptop,london,travel,0,...,0,amex,200,2968.75,password,0.1635,22,0,0,Non-Fraud

##### Überblick über Datentypen und Variablen

In diesem Schritt werden die enthaltenen Variablen sowie deren Datentypen analysiert.
Dabei wird zwischen numerischen und kategorischen Variablen unterschieden.

In [253]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49998 entries, 0 to 49997
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Transaction_ID                49998 non-null  str
 1   User_ID                       49998 non-null  str
 2   Transaction_Amount            49998 non-null  float64
 3   Transaction_Type              49998 non-null  str
 4   Account_Balance               49998 non-null  float64
 5   Amount_to_Balance_Ratio       49998 non-null  float64
 6   Device_Type                   49998 non-null  str
 7   Location                      49998 non-null  str
 8   Merchant_Category             49998 non-null  str
 9   IP_Address_Flag               49998 non-null  int64
 10  Previous_Fraudulent_Activity  49998 non-null  int64
 11  Daily_Transaction_Count       49998 non-null  int64
 12  Avg_Transaction_Amount_7d     49998 non-null  float64
 13  Failed_Transaction_Count_7d   49998 non-null  int64
 14  Card_Type                     49998 non-null  str
 15  Card_Age                      49998 non-null  int64
 16  Transaction_Distance          49998 non-null  float64
 17  Authentication_Method         49998 non-null  str
 18  Risk_Score                    49998 non-null  float64
 19  Hour                          49998 non-null  int64
 20  Is_Weekend                    49998 non-null  int64
 21  Fraud_Label                   49998 non-null  int64
 22  Fraud_Label_str               49998 non-null  str
dtypes: float64(6), int64(8), str(9)
memory usage: 8.8 MB

##### Numerische und kategorische Variablen identifizieren

In [254]:
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns
categorical_columns = df.select_dtypes(include=["object"]).columns

print("Numerische Variablen:")
print(numerical_columns)

print("\nKategorische Variablen:")
print(categorical_columns)

Numerische Variablen:
Index(['Transaction_Amount', 'Account_Balance', 'Amount_to_Balance_Ratio',
       'IP_Address_Flag', 'Previous_Fraudulent_Activity',
       'Daily_Transaction_Count', 'Avg_Transaction_Amount_7d',
       'Failed_Transaction_Count_7d', 'Card_Age', 'Transaction_Distance',
       'Risk_Score', 'Hour', 'Is_Weekend', 'Fraud_Label'],
      dtype='str')

Kategorische Variablen:
Index(['Transaction_ID', 'User_ID', 'Transaction_Type', 'Device_Type',
       'Location', 'Merchant_Category', 'Card_Type', 'Authentication_Method',
       'Fraud_Label_str'],
      dtype='str')

/var/folders/b8/sbt1y9vx2kl1whbqys3jf1wm0000gn/T/ipykernel_21491/832660727.py:2: Pandas4Warning:

For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.

##### Wichtige Variablen im Datensatz

| Variable | Beschreibung |
|---|---|
| Transaction_Amount | Höhe der Transaktion |
| Fraud_Label | Kennzeichnung Fraud / Non-Fraud |
| Payment_Method | Verwendete Zahlungsmethode |
| Device_Type | Verwendeter Gerätetyp |
| Merchant_Category | Händlerkategorie |
| Location | Standort der Transaktion |
| Failed_Transaction_Count_7d | Fehlgeschlagene Transaktionen innerhalb von 7 Tagen |
| Transaction_Hour | Uhrzeit der Transaktion |

#### 1.2 Deskriptive Kennzahlen

##### Allgemeine statistische Kennzahlen

Zur Beschreibung numerischer Variablen werden zentrale statistische Kennzahlen berechnet.
Dazu zählen Mittelwert, Median, Standardabweichung sowie Minimal- und Maximalwerte.

In [255]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Transaction_Amount,49998.0,99.414989,98.687263,1.000000e-02,28.680000,69.670000,138.857500,1174.140000
Account_Balance,49998.0,50292.621124,28760.096790,5.004800e+02,25355.425000,50381.445000,75112.362500,99998.310000
Amount_to_Balance_Ratio,49998.0,0.005300,0.019568,1.022004e-07,0.000597,0.001578,0.003814,1.052142
IP_Address_Flag,49998.0,0.050202,0.218364,0.000000e+00,0.000000,0.000000,0.000000,1.000000
Previous_Fraudulent_Activity,49998.0,0.098404,0.297863,0.000000e+00,0.000000,0.000000,0.000000,1.000000
Daily_Transaction_Count,49998.0,7.484999,4.039538,1.000000e+00,4.000000,7.000000,11.000000,14.000000
Avg_Transaction_Amount_7d,49998.0,255.267615,141.383308,1.000000e+01,132.082500,256.075000,378.030000,500.000000
Failed_Transaction_Count_7d,49998.0,2.003580,1.414273,0.000000e+00,1.000000,2.000000,3.000000,4.000000
Card_Age,49998.0,119.995960,68.984295,1.000000e+00,60.000000,120.000000,180.000000,239.000000
Transaction_Distance,49998.0,2499.119480,1442.021288,2.500000e-01,1256.452500,2490.620000,3746.312500,4999.930000
Risk_Score,49998.0,0.501538,0.287767,1.000000e-04,0.254000,0.502200,0.749500,1.000000
Hour,49998.0,11.516401,6.902378,0.000000e+00,6.000000,12.000000,17.000000,23.000000
Is_Weekend,49998.0,0.299652,0.458110,0.000000e+00,0.000000,0.000000,1.000000,1.000000
Fraud_Label,49998.0,0.321313,0.466985,0.000000e+00,0.000000,0.000000,1.000000,1.000000

##### Fraud-Rate des Datensatzes

Die Fraud-Rate beschreibt den Anteil betrügerischer Transaktionen
an allen vorhandenen Transaktionen.

In [256]:
fraud_rate = df["Fraud_Label"].mean()

print(f"Fraud Rate: {fraud_rate:.2%}")

Fraud Rate: 32.13%

##### Anzahl von Fraud- und Non-Fraud-Transaktionen

In [257]:
df["Fraud_Label_str"].value_counts()

Fraud_Label_str
Non-Fraud    33933
Fraud        16065
Name: count, dtype: int64

##### Durchschnittlicher Transaktionsbetrag nach Fraud-Status

In [258]:
df.groupby("Fraud_Label_str")[
    "Transaction_Amount"
].mean()

Fraud_Label_str
Fraud        99.696088
Non-Fraud    99.281907
Name: Transaction_Amount, dtype: float64

#### 1.3 Verteilungen und Visualisierungen

##### Verteilung der Fraud- und Non-Fraud-Transaktionen

Die Verteilung der Zielvariable zeigt,
wie stark Fraud- und Non-Fraud-Fälle im Datensatz vertreten sind.

In [259]:
fig = px.histogram(
    df,
    x="Fraud_Label_str",
    title="Distribution of Fraud and Non-Fraud Transactions"
)

fig.show()

##### Verteilung der Transaktionsbeträge

Die Verteilung der Transaktionsbeträge wird untersucht,
um typische Wertebereiche und mögliche Ausreißer sichtbar zu machen.

In [260]:
fig = px.histogram(
    df,
    x="Transaction_Amount",
    nbins=80,
    marginal="box",
    title="Distribution of Transaction Amounts"
)

fig.update_layout(
    xaxis_title="Transaction Amount",
    yaxis_title="Frequency"
)

fig.show()

##### Verteilung der Gerätetypen

Die Analyse der Gerätetypen zeigt,
welche Arten von Geräten für Transaktionen genutzt werden.

In [261]:
device_dist = (
    df["Device_Type"]
    .value_counts()
    .reset_index()
)

device_dist.columns = ["Device_Type", "Count"]

device_dist

  Device_Type  Count
0      tablet  16778
1      mobile  16639
2      laptop  16581

In [262]:
fig = px.bar(
    device_dist,
    x="Device_Type",
    y="Count",
    title="Distribution of Device Types"
)

fig.show()

##### Verteilung der Händlerkategorien

Die Händlerkategorien werden untersucht,
um dominante Kategorien im Datensatz zu identifizieren.

In [263]:
merchant_dist = (
    df["Merchant_Category"]
    .value_counts()
    .head(10)
    .reset_index()
)

merchant_dist.columns = ["Merchant_Category", "Count"]

merchant_dist

  Merchant_Category  Count
0          clothing  10033
1         groceries  10019
2            travel  10015
3       restaurants   9975
4       electronics   9956

In [264]:
fig = px.bar(
    merchant_dist,
    x="Merchant_Category",
    y="Count",
    title="Top Merchant Categories"
)

fig.show()

##### Zeitliche Verteilung der Transaktionen

Die zeitliche Verteilung zeigt,
zu welchen Tageszeiten die meisten Transaktionen stattfinden.

In [266]:
hourly = (
    df["Timestamp"]
    .value_counts()
    .sort_index()
    .reset_index()
)

hourly.columns = ["Hour", "Transactions"]

hourly

KeyError: 'Timestamp'

In [ ]:
fig = px.line(
    hourly,
    x="Hour",
    y="Transactions",
    markers=True,
    title="Transactions by Hour"
)

fig.show()

##### Fehlgeschlagene Transaktionen innerhalb von sieben Tagen

Die Verteilung fehlgeschlagener Transaktionen
innerhalb der letzten sieben Tage wird visualisiert.

In [ ]:
fig = px.histogram(
    df,
    x="Failed_Transaction_Count_7d",
    nbins=30,
    title="Distribution of Failed Transactions (7d)"
)

fig.show()

#### 1.4 Datenqualität

##### Untersuchung fehlender Werte

Die Datenqualität wird überprüft,
indem fehlende Werte innerhalb des Datensatzes identifiziert werden.

In [ ]:
df.isnull().sum()

##### Identifikation potenzieller Ausreißer

Mithilfe grafischer Darstellungen werden mögliche Ausreißer
innerhalb der Transaktionsbeträge untersucht.

In [ ]:
fig = px.box(
    df,
    y="Transaction_Amount",
    title="Outlier Detection: Transaction Amount"
)

fig.show()

##### Ausreißererkennung mit der IQR-Methode

Zur systematischen Erkennung von Ausreißern
wird die Interquartilsabstand-Methode (IQR) verwendet.

In [ ]:
Q1 = df["Transaction_Amount"].quantile(0.25)
Q3 = df["Transaction_Amount"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["Transaction_Amount"] < lower_bound) |
    (df["Transaction_Amount"] > upper_bound)
]

print(f"Anzahl Ausreißer: {len(outliers)}")

#### Zentrale Erkenntnisse

Die deskriptive Analyse liefert einen ersten Überblick über die Struktur,
Verteilungen und Eigenschaften des Datensatzes.

Dabei konnten Unterschiede zwischen Fraud-
und Non-Fraud-Transaktionen,
Auffälligkeiten bei Transaktionsbeträgen,
zeitliche Muster sowie potenzielle Ausreißer identifiziert werden.

In [ ]:
kpi = pd.DataFrame({
    "Kennzahl": [
        "Anzahl Transaktionen",
        "Anzahl Nutzer",
        "Fraud-Fälle",
        "Nicht-Fraud-Fälle",
        "Fraud Rate",
        "Durchschnittlicher Transaktionsbetrag",
        "Median Transaktionsbetrag",
        "Gesamtes Transaktionsvolumen",
        "Durchschnittlicher Risk Score"
    ],
    "Wert": [
        len(df),
        df["User_ID"].nunique(),
        int(df[target].sum()),
        int((1 - df[target]).sum()),
        f"{df[target].mean()*100:.2f}%",
        round(df["Transaction_Amount"].mean(), 2),
        round(df["Transaction_Amount"].median(), 2),
        round(df["Transaction_Amount"].sum(), 2),
        round(df["Risk_Score"].mean(), 4)
    ]
})
display(kpi)

In [ ]:
fig = px.histogram(
    df,
    x="Transaction_Amount",
    nbins=80,
    marginal="box",
    title="Distribution of Transaction Amounts"
)

fig.update_layout(
    xaxis_title="Transaction Amount",
    yaxis_title="Frequency"
)

fig.show()

Die Verteilung der Transaktionsbeträge zeigt typische Zahlungsgrößen, Ausreißer und mögliche Schiefe. In Fraud-Kontexten sind extreme Beträge besonders relevant.

In [ ]:
device_dist = (
    df["Device_Type"]
    .value_counts()
    .reset_index()
)

device_dist.columns = ["Device_Type", "Count"]

device_dist

In [ ]:
fig = px.bar(
    device_dist,
    x="Device_Type",
    y="Count",
    title="Distribution of Device Types"
)

fig.show()

In [ ]:
fig = px.box(
    df,
    x="Fraud_Label_str",
    y="Failed_Transaction_Count_7d",
    title="Failed Transactions in Last 7 Days by Class"
)

fig.show()

In [ ]:
payment_dist = (
    df["Card_Type"]
    .value_counts()
    .reset_index()
)

payment_dist.columns = ["Card_Type", "Count"]

payment_dist

In [ ]:
fig = px.pie(
    payment_dist,
    names="Card_Type",
    values="Count",
    title="Distribution of Payment Methods"
)

fig.show()

Sonstiges

In [ ]:
fig = px.histogram(
    df,
    x="Fraud_Label_str",
    title="Class Imbalance: Fraud vs. Non-Fraud"
)
fig.show()

In [ ]:
if "Location" in df.columns:
    loc = (
        df.groupby("Location", as_index=False)
        .agg(
            Transactions=("Transaction_ID", "count"),
            Fraud_Rate=("Fraud_Label", "mean")
        )
    )

    loc = loc[loc["Transactions"] >= 100] \
        .sort_values("Fraud_Rate", ascending=False) \
        .head(15)

    fig = px.bar(
        loc,
        x="Fraud_Rate",
        y="Location",
        orientation="h",
        title="Top Locations nach Fraud-Rate (min. 100 Transaktionen)"
    )
    fig.show()

In [ ]:
fig = px.box(
    df,
    x="Fraud_Label_str",
    y="Failed_Transaction_Count_7d",
    title="Failed Transactions (7d): Fraud vs Non-Fraud"
)
fig.show()

Diagnostische Analyse anhand Drill-Down-Prinzip

In [ ]:
loc = (
    df.groupby("Location", as_index=False)
    .agg(
        Transactions=("Transaction_ID", "count"),
        Fraud_Rate=("Fraud_Label", "mean")
    )
)

# nur stabile Segmente
loc = loc[loc["Transactions"] >= 100]

loc = loc.sort_values("Fraud_Rate", ascending=False)

fig = px.bar(
    loc.head(15),
    x="Fraud_Rate",
    y="Location",
    orientation="h",
    title="Top Locations nach Fraud Rate"
)
fig.show()

loc.head()

In [ ]:
selected_location = loc.iloc[0]["Location"]  # oder manuell setzen
print("Selected Location:", selected_location)

df_loc = df[df["Location"] == selected_location]

In [ ]:
device_agg = (
    df_loc.groupby("Device_Type")["Fraud_Label"]
    .mean()
    .reset_index()
)

fig = px.bar(
    device_agg,
    x="Device_Type",
    y="Fraud_Label",
    title=f"Fraud Rate by Device - {selected_location}"
)
fig.show()

In [ ]:
ip_agg = (
    df_loc.groupby("IP_Address_Flag")["Fraud_Label"]
    .mean()
    .reset_index()
)

ip_agg["IP_Address_Flag"] = ip_agg["IP_Address_Flag"].map({
    0: "Normal",
    1: "Suspicious"
})

fig = px.bar(
    ip_agg,
    x="IP_Address_Flag",
    y="Fraud_Label",
    title=f"Fraud Rate by IP Flag - {selected_location}"
)
fig.show()

In [ ]:
failed_agg = (
    df_loc.groupby("Failed_Transaction_Count_7d")["Fraud_Label"]
    .mean()
    .reset_index()
)

fig = px.line(
    failed_agg,
    x="Failed_Transaction_Count_7d",
    y="Fraud_Label",
    markers=True,
    title=f"Fraud Rate vs Failed Transactions - {selected_location}"
)
fig.show()

In [ ]:
combo = (
    df_loc.groupby(["Device_Type", "IP_Address_Flag"])["Fraud_Label"]
    .mean()
    .reset_index()
)

combo["IP_Address_Flag"] = combo["IP_Address_Flag"].map({
    0: "Normal",
    1: "Suspicious"
})

fig = px.bar(
    combo,
    x="Device_Type",
    y="Fraud_Label",
    color="IP_Address_Flag",
    barmode="group",
    title=f"Fraud Rate: Device + IP - {selected_location}"
)
fig.show()

IDK

In [ ]:
for loc_name in loc.head(3)["Location"]:
    print("\nAnalyzing:", loc_name)

    df_loc = df[df["Location"] == loc_name]

    print("Fraud Rate:", df_loc["Fraud_Label"].mean())
    print("Avg Failed Tx:", df_loc["Failed_Transaction_Count_7d"].mean())

In [ ]:
overall_fraud = df["Fraud_Label"].mean()

for loc_name in loc.head(3)["Location"]:
    df_loc = df[df["Location"] == loc_name]

    fraud_rate = df_loc["Fraud_Label"].mean()
    n = len(df_loc)

    print(f"\nLocation: {loc_name}")
    print(f"Fraud Rate: {fraud_rate:.3f}")
    print(f"Sample Size: {n}")
    print(f"Difference vs Overall: {fraud_rate - overall_fraud:.3f}")

In [ ]:
from scipy.stats import chi2_contingency
import pandas as pd

# Binning (interpretable für Business)
df["failed_bin"] = pd.cut(
    df["Failed_Transaction_Count_7d"],
    bins=[-1, 0, 1, 3, 5, 10, 100],
    labels=["0", "1", "2-3", "4-5", "6-10", "10+"]
)

# Contingency Table
table = pd.crosstab(df["failed_bin"], df["Fraud_Label"])

table

In [ ]:
chi2, p, dof, expected = chi2_contingency(table)

print("Chi2:", chi2)
print("p-value:", p)

In [ ]:
rate = (
    df.groupby("Failed_Transaction_Count_7d")["Fraud_Label"]
    .mean()
    .reset_index()
)

import plotly.express as px

fig = px.line(
    rate,
    x="Failed_Transaction_Count_7d",
    y="Fraud_Label",
    markers=True,
    title="Fraud Rate vs Failed Transactions (7d)"
)

fig.show()

In [ ]:
effect = df.groupby("Failed_Transaction_Count_7d")["Fraud_Label"].mean().reset_index()

fig = px.line(
    effect,
    x="Failed_Transaction_Count_7d",
    y="Fraud_Label",
    markers=True,
    title="Fraud Rate by Failed Transactions"
)

fig.show()

In [ ]:
df["Failed_Transaction_Count_7d"].value_counts().sort_index()

In [ ]:
effect[effect["Fraud_Label"] > effect["Fraud_Label"].median()]

In [ ]:
data_quality = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing": df.isna().sum().values,
    "missing_pct": (df.isna().mean().values * 100).round(2),
    "unique": [df[c].nunique() for c in df.columns]
})

display(data_quality)

print("Zeilen-Duplikate:", df.duplicated().sum())

if "Transaction_ID" in df.columns:
    print("Doppelte Transaction_ID:", df["Transaction_ID"].duplicated().sum())

target = "Fraud_Label"
print("Fraud-Verteilung:")
display(df[target].value_counts().rename("count").to_frame())
print("Fraud Rate:", round(df[target].mean() * 100, 2), "%")